baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Premier Property Management'
theme = 'property-management'

[params]
  description = "Professional property management services for residential and commercial properties"
  company_name = "Premier Property Management"
  phone = "(555) 123-4567"
  email = "info@premierpropertymgmt.com"
  address = "123 Business Ave, City, State 12345"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
