baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'HTX Property Management'
theme = 'property-management'

[params]
  description = "Professional property management services for residential and commercial properties"
  company_name = "HTX Property Management"
  email = "htxpropmanage@gmail.com"
  phone = "xiaohongshu Id: 94303120618"
  address = "Wechat Id: htxpropmanage"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
